# Bài tập về NumPy Array Iterating, Join & Split

Import thư viện

In [ ]:
import numpy as np

**Bài 1: Nối hai mảng 1D**

**Dữ liệu**:
```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```

**Yêu cầu đầu ra**:
1. Một mảng 1D: `[1 2 3 4 5 6]`
2. Một mảng 2D (2 hàng, 3 cột):
```
[[1 2 3]
 [4 5 6]]
```
3. Một mảng 1D khác (cách khác với cách 1).

**Bài 2: Nối mảng 2D theo hàng và cột**

**Dữ liệu**:
```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6]])
```

**Yêu cầu đầu ra**:
1. Nối **theo hàng** → mảng 3×2:
```
[[1 2]
 [3 4]
 [5 6]]
```
2. Nối **theo cột** (A với A) → mảng 2×4:
```
[[1 2 1 2]
 [3 4 3 4]]
```

**Bài 3: Tạo mảng 2D từ hai mảng 1D (thêm chiều mới)**

**Dữ liệu**:
```python
x = np.array([10, 20, 30])
y = np.array([40, 50, 60])
```

**Yêu cầu đầu ra**:
1. Mảng 2×3:
```
[[10 20 30]
 [40 50 60]]
```
2. Mảng 3×2:
```
[[10 40]
 [20 50]
 [30 60]]
```
3. In `shape` của từng mảng.

**Bài 4: Tách mảng 1D thành nhiều phần**

**Dữ liệu**:
```python
arr = np.arange(1, 9)   # [1 2 3 4 5 6 7 8]
```

**Yêu cầu đầu ra**:
1. 4 phần **bằng nhau** → mỗi phần 2 phần tử: `[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]`
2. 3 phần **không cần bằng nhau** → ví dụ: `[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]`

Tách mảng 2D theo hàng và cột**

**Dữ liệu**:
```python
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
```

**Yêu cầu đầu ra**:
1. Tách **theo cột** → 2 mảng 2×2:
```
[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]
```
2. Tách **theo hàng** → 2 mảng 1×4:
```
[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]])]
```