# **Buổi 10 – NumPy: Phần 2**

> **Mục tiêu**: Thành thạo các thao tác nâng cao trên mảng NumPy.

**Yêu cầu chung**:
- `import numpy as np`
- **Không dùng vòng lặp `for`** nếu có cách vectorized.

---

In [ ]:
import numpy as np

## **Bài 1: Nối hai mảng 1D**

**Dữ liệu**:
```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```

**Yêu cầu đầu ra**:
1. Một mảng 1D: `[1 2 3 4 5 6]`
2. Một mảng 2D (2 hàng, 3 cột):
```
[[1 2 3]
 [4 5 6]]
```
3. Một mảng 1D khác (cách khác với cách 1).

---

In [ ]:
# Bài 1 – Viết code của bạn ở đây



## **Bài 2: Nối mảng 2D theo hàng và cột**

**Dữ liệu**:
```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6]])
```

**Yêu cầu đầu ra**:
1. Nối **theo hàng** → mảng 3×2:
```
[[1 2]
 [3 4]
 [5 6]]
```
2. Nối **theo cột** (A với A) → mảng 2×4:
```
[[1 2 1 2]
 [3 4 3 4]]
```

---

In [ ]:
# Bài 2 – Viết code của bạn ở đây



## **Bài 3: Tạo mảng 2D từ hai mảng 1D (thêm chiều mới)**

**Dữ liệu**:
```python
x = np.array([10, 20, 30])
y = np.array([40, 50, 60])
```

**Yêu cầu đầu ra**:
1. Mảng 2×3:
```
[[10 20 30]
 [40 50 60]]
```
2. Mảng 3×2:
```
[[10 40]
 [20 50]
 [30 60]]
```
3. In `shape` của từng mảng.

---

In [ ]:
# Bài 3 – Viết code của bạn ở đây



## **Bài 4: Tách mảng 1D thành nhiều phần**

**Dữ liệu**:
```python
arr = np.arange(1, 9)   # [1 2 3 4 5 6 7 8]
```

**Yêu cầu đầu ra**:
1. 4 phần **bằng nhau** → mỗi phần 2 phần tử: `[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]`
2. 3 phần **không cần bằng nhau** → ví dụ: `[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]`

---

In [ ]:
# Bài 4 – Viết code của bạn ở đây



## **Bài 5: Tách mảng 2D theo hàng và cột**

**Dữ liệu**:
```python
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
```

**Yêu cầu đầu ra**:
1. Tách **theo cột** → 2 mảng 2×2:
```
[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]
```
2. Tách **theo hàng** → 2 mảng 1×4:
```
[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]])]
```

---

In [ ]:
# Bài 5 – Viết code của bạn ở đây



## **Bài 6: Tìm vị trí và giá trị thỏa điều kiện**

**Dữ liệu**:
```python
doanh_thu = np.array([85, 92, 78, 95, 88, 70])
```

**Yêu cầu đầu ra**:
1. **Chỉ số** (index) của các ngày có doanh thu **> 90 triệu**: `(array([1, 3]),)`
2. **Giá trị** doanh thu của các ngày đó: `[92 95]`

---

In [ ]:
# Bài 6 – Viết code của bạn ở đây



## **Bài 7: Sắp xếp mảng**

**Dữ liệu**:
```python
diem = np.array([67, 92, 78, 85, 96])
```

**Yêu cầu đầu ra**:
1. Mảng **tăng dần**: `[67 78 85 92 96]`
2. Mảng **chỉ số** tương ứng với thứ tự tăng dần: `[0 2 3 1 4]`
3. Mảng **giảm dần**: `[96 92 85 78 67]`

---

In [ ]:
# Bài 7 – Viết code của bạn ở đây



## **Bài 8: Lọc dữ liệu theo điều kiện**

**Dữ liệu**:
```python
nhiet_do = np.array([28, 35, 32, 38, 30, 29, 39])
```

**Yêu cầu đầu ra**:
1. Các ngày **có nhiệt độ ≥ 35°C**: `[35 38 39]`
2. Các ngày **nhiệt độ từ 30 đến 35°C** (bao gồm cả 30 và 35): `[35 32 30]`
3. **Số ngày** có nhiệt độ ≥ 35°C: `3`

---

In [ ]:
# Bài 8 – Viết code của bạn ở đây



## **Bài 9: Tạo mảng ngẫu nhiên**

**Yêu cầu đầu ra**:
1. Mảng **5 phần tử** ngẫu nhiên trong khoảng **[0, 1)** (ví dụ: `[0.23 0.76 0.49 0.12 0.89]`)
2. Mảng **5 phần tử** theo **phân phối chuẩn** (trung bình = 0, độ lệch chuẩn = 1) (ví dụ: `[-1.04 0.56 1.32 0.08 -0.67]`)
3. Mảng **6 số nguyên** ngẫu nhiên từ **1 đến 100** (bao gồm 100) (ví dụ: `[41 48 28 34 27 35]`)

**Lưu ý**: Kết quả ngẫu nhiên, chỉ cần đúng định dạng và phạm vi.

---

In [ ]:
# Bài 9 – Viết code của bạn ở đây



## **Bài 10: Xáo trộn và chọn ngẫu nhiên**

**Dữ liệu**:
```python
hs = np.array(['An', 'Bình', 'Cường', 'Dũng', 'Lan'])
```

**Yêu cầu đầu ra**:
1. Danh sách sau khi **xáo trộn** (mảng gốc thay đổi, ví dụ: `['Cường' 'Lan' 'An' 'Dũng' 'Bình']`)
2. **3 học sinh** được chọn ngẫu nhiên, không trùng (ví dụ: `['An' 'Dũng' 'Lan']`)
3. In cả hai kết quả.

---

In [ ]:
# Bài 10 – Viết code của bạn ở đây



---
**HOÀN TẤT!**

**Lưu ý**:
- Dùng `print()` để kiểm tra kết quả.
- Kết quả ngẫu nhiên có thể khác nhau mỗi lần chạy (trừ khi cố định seed).
- **Không dùng vòng lặp `for`** nếu có cách NumPy vectorized.
